package com.briup.apps.poll.bean;

public class QuestionnaireQuestion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_qq.id
     *
     * @mbg.generated Mon Jun 25 16:38:45 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_qq.questions_id
     *
     * @mbg.generated Mon Jun 25 16:38:45 CST 2018
     */
    private Long questionsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_qq.questionnaire_id
     *
     * @mbg.generated Mon Jun 25 16:38:45 CST 2018
     */
    private Long questionnaireId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_qq.id
     *
     * @return the value of poll_qq.id
     *
     * @mbg.generated Mon Jun 25 16:38:45 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_qq.id
     *
     * @param id the value for poll_qq.id
     *
     * @mbg.generated Mon Jun 25 16:38:45 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_qq.questions_id
     *
     * @return the value of poll_qq.questions_id
     *
     * @mbg.generated Mon Jun 25 16:38:45 CST 2018
     */
    public Long getQuestionsId() {
        return questionsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_qq.questions_id
     *
     * @param questionsId the value for poll_qq.questions_id
     *
     * @mbg.generated Mon Jun 25 16:38:45 CST 2018
     */
    public void setQuestionsId(Long questionsId) {
        this.questionsId = questionsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_qq.questionnaire_id
     *
     * @return the value of poll_qq.questionnaire_id
     *
     * @mbg.generated Mon Jun 25 16:38:45 CST 2018
     */
    public Long getQuestionnaireId() {
        return questionnaireId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_qq.questionnaire_id
     *
     * @param questionnaireId the value for poll_qq.questionnaire_id
     *
     * @mbg.generated Mon Jun 25 16:38:45 CST 2018
     */
    public void setQuestionnaireId(Long questionnaireId) {
        this.questionnaireId = questionnaireId;
    }
}